### ISSUE TITLE
サービスのドメイン

### ISSUE THREAD

**Issue by marshi** [houkago/deployboard-frontend#10]
ドメインどないしよ
ついでにパッケージ名も。

**Comment by stormcat24** [comment]
パッケージ名はdeployboardだけでいいんじゃないすかね。パッケージ名をドメインに使わないのが最近のトレンドかと

**Comment by marshi** [comment]
ほほぉ、ではパッケージ名はdeployboardでいきましょう。

**Comment by stormcat24** [comment]
いったんherokuるということでdeployboard.herokuapp.com
